### ISSUE TITLE
proto/lidar_frame.pb.h

### ISSUE THREAD

**Issue by natsume7** [HesaiTechnology/pandar-ros#1]
The "proto/lidar_frame.pb.h" is needed but missing ,can u help add it, thanks!

**Comment by trickyMan** [comment]
proto/lidar_frame.pb.h is generated by "pandar-ros/pandar_grabber/proto/lidar_frame.proto" , which is based on Google's protobuf. 

Did you include pandar_grabber/proto/CMakeLIsts.txt nomally?

"pandar_grabber/proto/CMakeLIsts.txt " is the cmake file to describe how to process the .proto files.

[CMakeLists.txt](https://github.com/HesaiTechnology/pandar-ros/blob/master/pandar_grabber/proto/CMakeLists.txt)

**Comment by taogashi** [comment]
Also make sure all the dependencies are installed. In your case they're protobuf-compiler and libprotobuf-dev. Run `protoc --version` to check if they were correctly installed.

**Comment by natsume7** [comment]
problem solved，thanks

**Comment by trickyMan** [comment]
Ok, So this issue will be closed.
