### ISSUE TITLE
驱动

### ISSUE THREAD

**Issue by deepmeng** [HesaiTechnology/pandar-ros#12]
这个驱动怎么用的，我编译后只改了Pandar40_points.launch， cloud_nodelet.launch两个文件的设备IP，结果没跑起来。一直停留在下图，求大神搭救。
![image](https://user-images.githubusercontent.com/8176780/38943221-6f90105a-4363-11e8-843a-ecbc75da5968.png)

**Comment by trickyMan** [comment]
在等待LiDAR的UDP点云数据.

**Comment by deepmeng** [comment]
雷达工作没问题，用了HesaiLidar-ros驱动中的p40p.launch能正常获取数据。但是这个驱动一直不工作。纳闷，有技术交流群组吗？能否加一下详细咨询？

**Comment by trickyMan** [comment]
pandar-ros 只接受Pandar40的数据, 不接受Pandar40P的数据. 目前我们没有交流群.

**Comment by trickyMan** [comment]
有可能你手上的LiDAR使用的是 40P 的格式.

**Comment by deepmeng** [comment]
谢谢解答！ 那有没有驱动可以同时pub  40p的packets和points？

**Comment by trickyMan** [comment]
我们去掉了这部分, 因为会引入延迟.

**Comment by deepmeng** [comment]
方便提供一下这部分功能吗？急需。。。

**Comment by trickyMan** [comment]
目前没有再维护了. 建议你用wireshark / tcpdump 录制lidar的pcap. 然后用ros 制定pcap_file参数,可以从PCAP读取点云.
