### ISSUE TITLE
Difference between repos "pandar-ros" and "HesaiLidar-ros"

### ISSUE THREAD

**Issue by Ckerrr** [HesaiTechnology/pandar-ros#13]
Excuse me, what are the difference between these two repos? 
If I am using the Pandar40 with ROS, which repo should I refer to?
Thanks.

**Comment by eros-ck** [comment]
Hell

**Comment by trickyMan** [comment]
HesaiLidar-ros is recommanded. The difference between 'pandar-ros'  and 'HesaiLidar-ros' is :grinning: 
1. HesaiLidar-ros is based on 'HesaiLidarSDK' ,  you can add 'HesaiLidarSDK' to your project easily.
2. HesaiLidar-ros support the packet structure of pandar40 and pandar40P. pandar-ros only support pandar40's.

If you use ROS and Pandar40 only. there is no difference for you.

**Comment by Ckerrr** [comment]
Thanks a lot. It's very helpful.

Issue closed
