### ISSUE TITLE
cloud.header.stamp

### ISSUE THREAD

**Issue by natsume7** [HesaiTechnology/pandar-ros#14]
pandar-ros/pandar_grabber/test/grabber_test.cpp line 51 获取到的cloud， 如何将其cloud.header.stamp 转换成正常时间 ，其stamp值为什么是19位的时间戳，既然是微妙级别的，不应该是16位的吗？因为想通过
time = cloud.header.stamp - pre_cloud.header.stamp
来计算点云帧的帧间时间差来计算检测目标的速度，所以想要获取此参数。

**Comment by trickyMan** [comment]
https://github.com/HesaiTechnology/pandar-ros/blob/master/pandar_grabber/src/pandar_grabber.cpp#L356
这里是计算点云时间的部分, 计算的规则是系统的秒 加上最后一个packet里面的微妙时间, 是一个 64bit 的数字, 这个项目仅仅展示了数据包该怎么解析, 时间戳部分是不可信任的, pandar_grabber 是一个非常老的项目. 

如果你们链接GPS 和 LiDAR, LiDAR会和GPS做时间同步. 推荐你们使用 HesaiLidarSDK: https://github.com/HesaiTechnology/HesaiLidarSDK 来开发, 里面有 pandar40 的 sample 程序. 给出的点云stamp是以秒为单位的 double. 譬如 1.0002s 等.

**Comment by trickyMan** [comment]
或者 pandar-ros , branch: vstyle-gps(default) 也是具备正确的时间戳解析. 不推荐你们使用 master 分支.

**Comment by natsume7** [comment]
我的应用场景里没有连接gps，仅仅是使用lidar采集实时点云数据，这样该如何获取解析出来的点云的cloud.header.stamp呢

**Comment by trickyMan** [comment]
这样也可以利用pandar-ros解析出来时间, 从0s开始, 您可以打印看看. 从pandar-ros启动,开始计算,单位为秒. 请使用 vstyle-gps 这个分支. 不要使用master.
