### ISSUE TITLE
不能使用rviz查看pcap点云

### ISSUE THREAD

**Issue by Abl4-auto** [HesaiTechnology/pandar-ros#15]
利用该代码运行launch读取pcap文件，但是无法使用rviz查看，能找到topic，但是无法找到fix frame

**Comment by trickyMan** [comment]
rostopic echo /pandar_points 看看是否有数据, 如果有, 应该是rviz配置的问题.
你试试:
Global Info 里面设置Fix Frame 为 pandar 试试
