### ISSUE TITLE
Official ROS Release

### ISSUE THREAD

**Issue by JWhitleyWork** [HesaiTechnology/pandar-ros#16]
Would it be possible for the maintainers of this repository to release it to the official ROS build farm? Instructions for doing so are included here: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

The process is not very straight-forward so I can help if any assistance is needed.

**Comment by trickyMan** [comment]
Sure, We need some time to follow the instructions , and release it after that. Thank you for your suggestion.
