### ISSUE TITLE
grabber_test  viewer.showCloud 失败

### ISSUE THREAD

**Issue by natsume7** [HesaiTechnology/pandar-ros#2]
你好，我在运行grabber_test时 ， line91  处 interface.raw2PointCloud(*scan , point_cloud_ptr)，point_cloud_prt是可正常保存为点云数据，
  但line92 处 this->viewer.showCloud (point_cloud_ptr)却无法显示点云
 调试 解析出第二帧点云时，至pandar_grabber.cpp line560处 current_scan_raw_.reset (new hesai::Scan ())报(vtkRenderingOpenGL2-7.0-gd.dll)处有未经处理的异常:  0xC0000005:  读取位置 0x000000000CB48000 时发生访问冲突，这该如何解决呢？

**Comment by taogashi** [comment]
你好！current_scan_raw_是boost::shared_ptr，current_scan_raw_.reset (new hesai::Scan ())的意思是将current_scan_raw_重置为空的内容，与vtk没有关系的。请问你所用的电脑在安装完PCL后成功显示过点云吗？PCL的例程是否可以正常运行？

**Comment by natsume7** [comment]
恩，pcl的例程时可正常运行，点云可正常显示的。
程序运行时，解析完第二帧后就报” 0x000007FEE481F289 (vtkRenderingOpenGL2-7.0-gd.dll) (viewHesai.exe 中)处有未经处理的异常:  0xC0000005:  读取位置 0x0000000009BBC000 时发生访问冲突”，期间点云没有显示，
cloud_viewer无法显示后，换用pcl_visualzier  ，有在
SimpleHDLGrabber  pcl::visualization::CloudViewer viewer处替换用pcl::visualization::PCLVisualizer viewer并初始化，在rawScan this->viewer.showCloud(point_cloud_ptr)处，改用if(viewer.updatePointCloud<pcl::PointXYZI>(point_cloud_ptr))
	  viewer.addPointCloud<pcl::PointXYZI>(point_cloud_ptr);
viewer.spinOnce()；程序运行到viewer.spinOnce处无法向下执行，此句注释后，正常执行。整个代码其它测试了没有问题，解析得到的点云数据在其他程序中可正常显示，就是在此可视化点云时遇到了问题，你觉得可能是什么原因呢？

**Comment by taogashi** [comment]
你好，我们推荐使用ubuntu环境运行这些代码。如果你因为某些原因只能在windows环境中使用本项目，能否告知你的环境配置，包括PCL、protobuf、pcap等库的安装方法，以便我们进行相应的测试？

**Comment by natsume7** [comment]
PCL 装的是all in one 1.80， protobuf  是protobuf-v120.2.6.1，pcap 是WpdPack_4_1_2，这些库的配置是在vs2013中进行的，在vc++目录中的包含目录、库目录指定相应的路径，在链接器的输入-> 附加依赖项加入相应的lib，如此进行常规的配置后运行代码。恩，你方便的话可以在window平台上测试一下代码，看看有无异常。

**Comment by the-sword** [comment]
@natsume7  你好，请问你使用这个程序最后可以显示点云吗？这个lidar获取的数据格式pcap格式，请问你对这个格式是怎么解析的？最近使用这个产品，相关文档太少了，谢谢了

**Comment by trickyMan** [comment]
[Pcap 是网络抓包的格式](https://en.wikipedia.org/wiki/Pcap)，这个软件是能够显示点云的，解析方式先源代码里面也有示例，先使用libpcap解析出来数据包，再根据LiDAR的UDP Payload结构描述:[User Manual](http://www.hesaitech.com/un-file.html)解析数据，再转换成PCL格式的点云数据，并显示。

这正是这个软件做的事情。

**Comment by trickyMan** [comment]
Pandar-ros 的作用在于集成进[ROS](http://www.ros.org/)，在ROS系统内广播消息，通过ros   @@的[rviz](http://wiki.ros.org/rviz)可以显示出来。广播消息，可以缓解用户集成LiDAR解析数据的麻烦，直接接受ROS节点的消息，可以获得点云结构，然后直接做算法了。 @the-sword

**Comment by the-sword** [comment]
@trickyMan 我是用HesaiTechnology/Pandar40Tools这个源码可以解析到对应的distance 和intensity数据，但是后面转换PCL格式不太明白，可不可以在指导下？或者有什么资料，十分感谢

**Comment by trickyMan** [comment]
@the-sword distance 和 intensity是数据里面的内容，根据User Manual的数据格式中，还包含了每组数据的水平转角，每个激光器都拥有仰角数据（每台LiDAR因为装调&标定误差，都会提供标定文件，其中包含这台LiDAR真实的仰角，水平转角的offset), 如此一来，可以建立坐标系（水平角度，仰角角度，距离信息），算出空间中x,y,z坐标，新建CloudPoint<Point> 结构体，push_back 每个坐标点就可以了。

Pandar40Tools Parser模块的头文件中也提供了参考 ， 仰角，水平偏角的数据（仅供参考，以实际LiDAR的标定文件为准（一般偏移 < 0.1 度）

如果你缺少你的LiDAR的标定文件，请向我们销售获取。

[rawdata.cc ](https://github.com/HesaiTechnology/pandar-ros/blob/vstyle/pandar_pointcloud/src/lib/rawdata.cc )里面有如何转换成PCL数据结构的具体计算方法。
