### ISSUE TITLE
能否说明下可以运行该源码的环境？

### ISSUE THREAD

**Issue by the-sword** [HesaiTechnology/pandar-ros#5]
例如ubuntu的版本，ROS，PCL等环境，我在ubuntu14上跑的时候发现在cmake   pandar_driver时候出现错误

CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pandar_msgs" with
  any of the following names:

    pandar_msgsConfig.cmake
    pandar_msgs-config.cmake

  Add the installation prefix of "pandar_msgs" to CMAKE_PREFIX_PATH or set
  "pandar_msgs_DIR" to a directory containing one of the above files.  If
  "pandar_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)

我按照上述方式改了之后，还是报错。
请问是什么原因呢？谢谢

**Comment by trickyMan** [comment]
不是这样使用的，安装ros 和 pcap就可以运行起来了。百度ros官网，然后apt get去安装，apt get 安装pcap，掌握基本的ros编译，catkin_make，然后roslaunch跑起来就可以了。pcl会被ros默认安装上的。

你需要补充的是ROS的知识，和传统cmake去编译差别很大，当然ROS也基于cmake，ros在cmake基础上又包装了一层。

祝好。

**Comment by trickyMan** [comment]
建议Ubuntu16.04,  ros kinect，安装运行，基本上没出现过问题。。。

**Comment by the-sword** [comment]
@trickyMan 
好的  感谢这么及时的回复，刚接触这块，很多不了解的。

**Comment by trickyMan** [comment]
请问您是哪一位客户？

**Comment by the-sword** [comment]
@trickyMan 深圳大学的
